spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/usuarios?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: "root"
    password: "negro"
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: msql
    hikari:
      maximum-pool-size: 25
      connection-timeout: 15000
      idle-timeout: 300000
      max-lifetime: 900000

client:
  retry: 1

